spring:
  application:
    name: transaction-service
  docker:
    compose:
      file: transaction-service/docker-compose.yml
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
  rabbitmq:
    username: gpnUser
    password: anotherOnePassword
    virtual-host: /
  jpa:
    open-in-view: false

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

custom:
  message-broker:
    exchange: transaction.service.exchange
    publish-queues:
      transaction-created:
        routing-key: transaction.is.created
      transaction-create-failed:
        routing-key: transaction.create.failed
      transaction-completed:
        routing-key: transaction.is.completed
    listen-queues:
      complete-transaction-command:
        name: complete.transaction.command
      create-transaction-command:
        name: create.transaction.command
  jwt:
    publicKeyPath: /tmp/public.key
