spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 465
    username:
    password:
    ssl:
      enabled: true
  rabbitmq:
    username: gpnUser
    password: anotherOnePassword
    virtual-host: vhost

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

custom:
  rabbitmq:
    listen-queues:
      user-registration:
        name: user.registration.queue
      code-generation:
        name: code.generation.queue


