spring:
  application:
    name: mail-service
  mail:
    host: smtp.gmail.com
    port: 465
    username: dailyanyelse@gmail.com
    password: cvkw krih rlqd trkh
    ssl:
      enabled: true
  rabbitmq:
    username: gpnUser
    password: anotherOnePassword
    virtual-host: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

custom:
  rabbitmq:
    listen-queues:
      user-welcome:
        name: user.welcome.queue
      code-generation:
        name: code.generation.queue


