spring:
  application:
    name: auth-service
  docker:
    compose:
      enabled: true
      file: ./authentication-service/docker-compose.yml
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/changelog/db.changelog-master.yml

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
  instance:
    hostname: localhost

server:
  port: 0
custom:
  jwt:
    keySize: 2048
    privateKeyPath: /tmp/private.key
    publicKeyPath: /tmp/public.key
#
#logging:
#  pattern:
#    console: "%d{HH:mm:ss} | %-5level | %logger{1.} | %msg%n"