services:
  gpn-case-auth-database:
    image: postgres:17
    container_name: gpn.case.auth.database
    environment:
      POSTGRES_DB: gpnCaseAuthDatabase
      POSTGRES_USER: gpnUser
      POSTGRES_PASSWORD: yetAnotherPassword
    ports:
      - "5433:5432"